config/routes.rb
Blog::Application.routes.draw do

  root :to => 'kevin_blogs#index'

  resources :kevin_blogs
  
  namespace :admin do
    root :to => "access#login"
    
    get "access/menu"
    get "access/login"
    
    match "access/attempt_login"
    match "access/logout"
    
    resources :categories
    resources :users 
  end
  
  match 'about_us/index' => 'about_us#index', :as => :about_us
  match 'kevin_blogs/:id/list' => 'kevin_blogs#list', :as => :list
  match 'kevin_blogs/:id/comment' => 'kevin_blogs#comment', :as => :comment

  match ':controller(/:action(/:id))(.:format)'
end

app/models/kevin_blog.rb
class KevinBlog < ActiveRecord::Base
  attr_accessible :body, :category_id, :created_at, :created_by, :post, :state, :tag, :title, :updated_at, :updated_by
  
  belongs_to :user
  belongs_to :category
  has_many :comments
  
  def find_username(id="")
    return Admin::User.find(id).username
  end
  
  scope :category, lambda { |category_id| where("category_id = ?", category_id ) }
end

app/controllers/kevin_blogs_controller.rb
class KevinBlogsController < ApplicationController

  layout "front_page"

  # GET /kevin_blogs
  # GET /kevin_blogs.json
  def index
    @kevin_blogs = KevinBlog.all
    @categories = Admin::Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kevin_blogs }
    end
  end
  
  def list
    @kevin_blogs = KevinBlog.category(params[:id])
    @categories = Admin::Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kevin_blogs }
    end
  end

  # GET /kevin_blogs/1
  # GET /kevin_blogs/1.json
  def show
    @kevin_blog = KevinBlog.find(params[:id])
    @comment = @kevin_blog.comments
    @categories = Admin::Category.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kevin_blog }
    end
  end

  # GET /kevin_blogs/new
  # GET /kevin_blogs/new.json
  def new
    @kevin_blog = KevinBlog.new
    @categories = Admin::Category.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kevin_blog }
    end
  end

  # GET /kevin_blogs/1/edit
  def edit
    @kevin_blog = KevinBlog.find(params[:id])
    @categories = Admin::Category.all
  end

  # POST /kevin_blogs
  # POST /kevin_blogs.json
  def create
    @kevin_blog = KevinBlog.new(params[:kevin_blog])
    @kevin_blog.user_id = session[:user_id]
    respond_to do |format|
      if @kevin_blog.save
        format.html { redirect_to @kevin_blog, notice: 'Kevin blog was successfully created.' }
        format.json { render json: @kevin_blog, status: :created, location: @kevin_blog }
      else
        format.html { render action: "new" }
        format.json { render json: @kevin_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kevin_blogs/1
  # PUT /kevin_blogs/1.json
  def update
    @kevin_blog = KevinBlog.find(params[:id])

    respond_to do |format|
      if @kevin_blog.update_attributes(params[:kevin_blog])
        format.html { redirect_to @kevin_blog, notice: 'Kevin blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kevin_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kevin_blogs/1
  # DELETE /kevin_blogs/1.json
  def destroy
    @kevin_blog = KevinBlog.find(params[:id])
    @kevin_blog.destroy

    respond_to do |format|
      format.html { redirect_to kevin_blogs_url }
      format.json { head :no_content }
    end
  end
  
  def comment
    KevinBlog.find(params[:id]).comments.create(params[:comment])
    flash[:notice] = "OK! You do it."
    redirect_to :action => "show", :id => params[:id]
  end

end

app/helpers/kevin_blogs_helper.rb
module KevinBlogsHelper
end

app/views/kevin_blogs/_comment.html.erb
<div class="comment">
	<h2>Comment</h2>

	<% for comment in @kevin_blog.comments %>
	   <%= comment.content%>  <hr />
	<% end %>


	<%=form_for @comment.new, :url => comment_path(@kevin_blog), :html => { :method => :put } do |f|%>
	  <%= f.text_area(:content, :size=>"30x5")%>
	  <%= f.submit %>
	<% end %>
</div>

app/views/kevin_blogs/_form.html.erb
<div class="art-Post-tl"></div>
<div class="art-Post-tr"></div>
<div class="art-Post-bl"></div>
<div class="art-Post-br"></div>
<div class="art-Post-tc"></div>
<div class="art-Post-bc"></div>
<div class="art-Post-cl"></div>
<div class="art-Post-cr"></div>
<div class="art-Post-cc"></div>
<div class="art-Post-body">
<div class="blog">
  <%= form_for(@kevin_blog) do |f| %>
  <% if @kevin_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kevin_blog.errors.count, "error") %> prohibited this kevin_blog from being saved:</h2>

      <ul>
      <% @kevin_blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :publish %><br />
    <%= f.check_box :state %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category_id, @categories.collect{|c|[ c.category, c.id ]}.unshift(["==Please select a category==", 0])%>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.date_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br />
    <%= f.date_select :updated_at %>
  </div>
  <div class="field">
    <%= f.label :updated_by %><br />
    <%= f.text_field :updated_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
  </div>

app/views/kevin_blogs/_kevin_blog.html.erb
<div class="art-Post">
<div class="art-Post-tl"></div>
<div class="art-Post-tr"></div>
<div class="art-Post-bl"></div>
<div class="art-Post-br"></div>
<div class="art-Post-tc"></div>
<div class="art-Post-bc"></div>
<div class="art-Post-cl"></div>
<div class="art-Post-cr"></div>
<div class="art-Post-cc"></div>
<div class="art-Post-body">
	<div class="art-Post-inner art-article">
		<div class="art-PostMetadataHeader">
			<h2 class="art-PostHeaderIcon-wrapper">
				<span class="art-PostHeader"><%= link_to kevin_blog.title, kevin_blog, :title=> kevin_blog.title %></span>
			</h2>
			<div class="art-PostHeaderIcons art-metadata-icons">
			<img width="18" height="18" alt="" src="../images/PostDateIcon.png"><%= kevin_blog.created_at.to_s(:long) %> |
			<img width="12" height="14" alt="" src="../images/PostAuthorIcon.png">Author: <%= link_to Admin::User.find_by_id(kevin_blog.user_id).username, "#" %>
		</div>
	</div>
	<div class="art-PostContent">
		<p>
			<%= kevin_blog.body %>
		</p>
	</div>
	<div class="cleared"></div>
	<div class="art-PostMetadataFooter">
		<div class="art-PostFooterIcons art-metadata-icons">
			<img width="18" height="18" alt="" src="../images/PostCategoryIcon.png">Posted in <%= Admin::Category.find_by_id(kevin_blog.category_id).category %> | 
			<img width="18" height="18" alt="" src="../images/PostTagIcon.png"> Tags:  tag | 
			<img width="18" height="18" alt="" src="../images/PostCommentsIcon.png"><%= link_to "#{kevin_blog.comments.length} Comments ?", kevin_blog %>
			<%if session[:user_id]%>(<%= link_to 'Edit', edit_kevin_blog_path(kevin_blog) %>||<%= link_to 'Destroy', kevin_blog, method: :delete, data: { confirm: 'Are you sure?' } %>)<% end %>
		</div>
	</div>
	</div>
</div>
</div>

app/views/kevin_blogs/edit.html.erb
<%= render 'form' %>

app/views/kevin_blogs/index.html.erb
						<%= render :partial => "kevin_blog", :collection => @kevin_blogs.reverse%>
						<div class="art-Post">
							<div class="art-Post-tl"></div>
							<div class="art-Post-tr"></div>
							<div class="art-Post-bl"></div>
							<div class="art-Post-br"></div>
							<div class="art-Post-tc"></div>
							<div class="art-Post-bc"></div>
							<div class="art-Post-cl"></div>
							<div class="art-Post-cr"></div>
							<div class="art-Post-cc"></div>
							<div class="art-Post-body">
								<div class="art-Post-inner art-article">
									<div class="art-PostContent">
										<div class="navigation">
											<div class="alignleft"><%= link_to "« Other Entries", root_path%></div>
											<div class="alignright"></div>
											</div>
										</div>
									<div class="cleared"></div>
									</div>
								</div>
						</div>
					
				

app/views/kevin_blogs/list.html.erb
						<%= render :partial => "kevin_blog", :collection => @kevin_blogs.reverse%>
						<div class="art-Post">
							<div class="art-Post-tl"></div>
							<div class="art-Post-tr"></div>
							<div class="art-Post-bl"></div>
							<div class="art-Post-br"></div>
							<div class="art-Post-tc"></div>
							<div class="art-Post-bc"></div>
							<div class="art-Post-cl"></div>
							<div class="art-Post-cr"></div>
							<div class="art-Post-cc"></div>
							<div class="art-Post-body">
								<div class="art-Post-inner art-article">
									<div class="art-PostContent">
										<div class="navigation">
											<div class="alignleft"><%= link_to "« Other Entries", root_path%></div>
											<div class="alignright"></div>
											</div>
										</div>
									<div class="cleared"></div>
									</div>
								</div>
						</div>
					
				

app/views/kevin_blogs/new.html.erb
<%= render 'form' %>

app/views/kevin_blogs/show.html.erb
<p id="notice"><%= notice %></p>

<%= render :partial => "kevin_blog", :object => @kevin_blog%>

<%= render :partial => "comment", :object => @kevin_blog%>