config/routes.rb
Blog::Application.routes.draw do

  root :to => 'kevin_blogs#index'

  resources :kevin_blogs
  
  namespace :admin do
    root :to => "access#login"
    
    get "access/menu"
    get "access/login"
    
    match "access/attempt_login"
    match "access/logout"
    
    resources :categories
    resources :users 
  end
  
  match 'about_us/index' => 'about_us#index', :as => :about_us
  match 'kevin_blogs/:id/list' => 'kevin_blogs#list', :as => :list
  match 'kevin_blogs/:id/comment' => 'kevin_blogs#comment', :as => :comment

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/front_page.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><%= @html_title.to_s %></title>
	<%= stylesheet_link_tag("kevin_blogs", "scaffolds", :media=>"all")%>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="main">
		<div class="sheet">
			<div class="art-Sheet-tl"></div>
			<div class="art-Sheet-tr"></div>
			<div class="art-Sheet-bl"></div>
			<div class="art-Sheet-br"></div>
			<div class="art-Sheet-tc"></div>
			<div class="art-Sheet-bc"></div>
			<div class="art-Sheet-cl"></div>
			<div class="art-Sheet-cr"></div>
			<div class="art-Sheet-cc"></div>
			<div class="art-Sheet-body">
				<div class="art-nav">
					<div class="l"></div>
					<div class="r"></div>
					<div class="art-nav-center">
						<ul class="art-menu">
							<li>
								<%= link_to "<span class='l'></span><span class='r'></span><span class='t'>Home</span>".html_safe, root_path, :class=>"active" %>
							</li>
							<li><span class="art-menu-separator"></span></li>
							<li>
								<%= link_to "<span class='l'></span><span class='r'></span><span class='t'>About Us</span>".html_safe, about_us_path  %>
							</li>
							<% if session[:user_id]%><li><span class="art-menu-separator"></span></li><% end %>
							<li>
								<%= link_to "<span class='l'></span><span class='r'></span><span class='t'>New Kevin blog</span>".html_safe, new_kevin_blog_path if session[:user_id] %>
							</li>
						</ul>
					</div>
				</div>
				<div class="art-Header">
					<div class="art-Header-jpeg"></div>
					<div class="art-Logo">
						<h1 class="art-Logo-name" id="name-text">
							<%= link_to "kevin's blog", root_path%></h1>
						<div class="art-Logo-text" id="slogan-text">
							Today is your day…</div>
					</div>
				</div>
				<div class="art-contentLayout">
					<!-- art content begin -->
					<div class="art-content">
						<%=yield%>
					</div>
					<!-- art content end -->
					<div class="art-sidebar1">
						<%= render :partial => "common/login"%>
						<%= render :partial => "common/category"%>
					</div>
				</div>
				<div class="cleared"></div>
				<div class="art-Footer">
					<div class="art-Footer-inner">
						<a title="RSS" class="art-rss-tag-icon" href="#"></a>
						<div class="art-Footer-text">
							<p><a href="#">Contact Us</a> | <a href="#">Terms of Use</a> | <a href="#">Trademarks</a> | <a href="#">Privacy Statement</a><br>Copyright &copy; 2009 Your Blog Title. All Rights Reserved.</p>
						</div>
					</div>
					<div class="art-Footer-background">
					</div>
				</div>
			</div>
		</div>
		<div class="cleard"></div>
		<p class="art-page-footer">
				<b>Powered By:</b> <a href="#">Kevin</a> |
				<a href="#">Entries (RSS)</a> |
				<a href="#">Comments (RSS)</a> |
				<b>Designed By:</b> Kevin 
		</p>
	</div>
</body>
</html>